<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_baz</name>
   <tag></tag>
   <elementGuidId>18b9ffca-a9ae-4d41-99e6-eb80c9e64808</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cecd5af0-2071-013c-2750-368f773bffa2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cecd5af0-2071-013c-2750-368f773bffa2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e8614458-c807-43f9-8da6-a5fa24bab068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cecd5af0-2071-013c-2750-368f773bffa2</value>
      <webElementGuid>2a5ec97d-6d31-4f34-9fe5-7e45780520fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button alert</value>
      <webElementGuid>dfe51136-6360-48a3-89a5-fdac7350b964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>baz</value>
      <webElementGuid>c744eff8-6c6d-43d9-9940-b1bd700e2f86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cecd5af0-2071-013c-2750-368f773bffa2&quot;)</value>
      <webElementGuid>0452725b-8160-47e9-afb1-892dd7b6d17c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cecd5af0-2071-013c-2750-368f773bffa2']</value>
      <webElementGuid>8882e194-d125-44e4-98aa-dbaebf256dee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div/div/div/a[2]</value>
      <webElementGuid>9fa9472c-42b9-4887-ab01-0ac4a53267c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'baz')]</value>
      <webElementGuid>1de2f4c3-7b18-4dd9-a548-b202943b993f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bar'])[1]/following::a[1]</value>
      <webElementGuid>26f4eb71-826e-4075-bee2-ac9634a828b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Challenging DOM'])[1]/following::a[2]</value>
      <webElementGuid>32114120-3279-48c8-b0b3-fb50a95f38e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bar'])[2]/preceding::a[1]</value>
      <webElementGuid>3fd0b1d3-157c-4479-b0cd-6aad9324f5de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lorem'])[1]/preceding::a[2]</value>
      <webElementGuid>6e4cc7ca-4821-40ea-b775-59e8631f699c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='baz']/parent::*</value>
      <webElementGuid>cb6af45c-9ea4-4fac-8289-28de58eaff85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[3]</value>
      <webElementGuid>101c5330-4083-4af4-ac23-e033faed74f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>2a8fdab4-ca1c-4ac6-9d39-59a7ee6ab6dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'cecd5af0-2071-013c-2750-368f773bffa2' and (text() = 'baz' or . = 'baz')]</value>
      <webElementGuid>5141d8bd-4fc5-4100-9690-5aecfadbae09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
