<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_foo</name>
   <tag></tag>
   <elementGuidId>ed3eb59c-128f-480a-85ac-a56c70a41a08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cc66c740-2071-013c-273a-368f773bffa2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cc66c740-2071-013c-273a-368f773bffa2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1292cfbf-d277-4f48-9905-f270ed0995a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cc66c740-2071-013c-273a-368f773bffa2</value>
      <webElementGuid>6473d223-d620-4328-9e12-c84ee4859df6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>decaf099-6669-4886-b867-67b527617247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>foo</value>
      <webElementGuid>6497d7c7-f38a-4082-a147-f94a64a64bc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cc66c740-2071-013c-273a-368f773bffa2&quot;)</value>
      <webElementGuid>b25bd704-fcd6-4ecb-8aa5-4b073f93fc04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cc66c740-2071-013c-273a-368f773bffa2']</value>
      <webElementGuid>4fa3f469-d621-4b9b-a015-08108e085405</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div/div/div/a</value>
      <webElementGuid>267157d9-e2e2-46a0-be6d-299d61141779</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'foo')]</value>
      <webElementGuid>c7d924df-cdc4-4bd3-b53b-0024a6b560e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Challenging DOM'])[1]/following::a[1]</value>
      <webElementGuid>d5f530e3-3998-471f-aeab-571c04564f33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bar'])[1]/preceding::a[1]</value>
      <webElementGuid>b204f055-8358-4a56-8b4b-a44218094af4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='foo'])[2]/preceding::a[2]</value>
      <webElementGuid>c8a5bc70-a3e9-437b-bced-cfdf2c388892</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='foo']/parent::*</value>
      <webElementGuid>2a391d5e-5e92-4cdd-adbb-d6a386e4399e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[2]</value>
      <webElementGuid>e46a386c-73fa-4652-96b3-b4dece98b5ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a</value>
      <webElementGuid>51ff8550-2506-4aa7-84fb-55d22471751c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'cc66c740-2071-013c-273a-368f773bffa2' and (text() = 'foo' or . = 'foo')]</value>
      <webElementGuid>ded94458-2bad-4a2e-b8a5-1acfe571707d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
