<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_qux</name>
   <tag></tag>
   <elementGuidId>008b9e4f-a497-4e60-90f0-61cd0b75f328</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#d0dbbe60-2071-013c-2766-368f773bffa2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='d0dbbe60-2071-013c-2766-368f773bffa2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>32f71057-2f55-4ff0-9760-c65e3b2f4b9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>d0dbbe60-2071-013c-2766-368f773bffa2</value>
      <webElementGuid>31dd143f-d1be-4225-8228-2b1538c3d5ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button success</value>
      <webElementGuid>1b048954-ffdb-43d2-beaf-c42d88725008</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>qux</value>
      <webElementGuid>24c02464-eccc-45e0-bf52-819ff4b09eff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;d0dbbe60-2071-013c-2766-368f773bffa2&quot;)</value>
      <webElementGuid>7e6297ce-70a4-4b04-9dd5-e2a928f41f0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='d0dbbe60-2071-013c-2766-368f773bffa2']</value>
      <webElementGuid>8feb9cdd-9368-466f-a9ae-7b5cf91370b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div/div/div/a[3]</value>
      <webElementGuid>7fd6b0ac-0dc7-4fd8-9e3c-25b581507764</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'qux')])[3]</value>
      <webElementGuid>5e2e8c1e-2743-42ea-807d-7b8b17d87ed8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='qux'])[2]/following::a[1]</value>
      <webElementGuid>88207e4e-6f0b-4322-8ba4-86917b6bc9d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='qux'])[1]/following::a[2]</value>
      <webElementGuid>698502a1-9ee8-4674-877f-a7602a21b58c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lorem'])[1]/preceding::a[1]</value>
      <webElementGuid>55a76fbe-f713-47bb-b1f6-40d0327609b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ipsum'])[1]/preceding::a[1]</value>
      <webElementGuid>0e8ac4f2-4341-4e72-9685-951147240181</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[4]</value>
      <webElementGuid>a6ad5bec-a717-4898-9d60-dd4e51dc23ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]</value>
      <webElementGuid>4e6d8826-0ff7-4c42-83f0-8838a80550b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'd0dbbe60-2071-013c-2766-368f773bffa2' and (text() = 'qux' or . = 'qux')]</value>
      <webElementGuid>cb0e3d75-2222-44ca-95b6-5048a81173ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
