<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Delete</name>
   <tag></tag>
   <elementGuidId>3d6752b7-dc1c-4637-a38e-39be375f5e08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.added-manually</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@onclick='deleteElement()']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c6b4c832-a6cc-44b1-b3a1-709e22110b94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>added-manually</value>
      <webElementGuid>b6b0036f-a8e8-4ef2-b977-46a913619db1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>deleteElement()</value>
      <webElementGuid>e1450965-7f4e-47bd-a2a0-0caad4490231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>8c95e7f3-fed0-4cff-a0cc-5f110147c956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;elements&quot;)/button[@class=&quot;added-manually&quot;]</value>
      <webElementGuid>5f0b6f24-0501-48cf-9c50-0cba4c30db50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@onclick='deleteElement()']</value>
      <webElementGuid>81c1a48d-65f7-43e5-b224-fec806d64bea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='elements']/button</value>
      <webElementGuid>c70c7ea6-052b-4ea4-ac76-11c7c6be6630</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Element'])[1]/following::button[1]</value>
      <webElementGuid>e713ad84-42c0-400c-9ddc-71a077dbd649</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add/Remove Elements'])[1]/following::button[2]</value>
      <webElementGuid>66ef1af4-9b1b-47fb-befc-07fc37d8f5ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Elemental Selenium'])[1]/preceding::button[1]</value>
      <webElementGuid>cd4834a4-43f5-463d-9e62-e79762bda1d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Delete']/parent::*</value>
      <webElementGuid>72cbd9fd-bf0e-48e2-9844-a0c6845df7aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/button</value>
      <webElementGuid>3cbb8abe-7212-4bad-92be-e89a2560f9c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Delete' or . = 'Delete')]</value>
      <webElementGuid>8dd9425d-e0c2-42c5-adc1-bac0fbfb1314</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
