<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Context Menu_hot-spot</name>
   <tag></tag>
   <elementGuidId>85a9538a-a183-4d77-b57c-ca7430c84b8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#hot-spot</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hot-spot']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b2c11823-c3d3-4e49-8202-1dcd6a754855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hot-spot</value>
      <webElementGuid>12ca8062-7cf7-43e9-a66b-fc953970dea8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oncontextmenu</name>
      <type>Main</type>
      <value>displayMessage()</value>
      <webElementGuid>003d6a1d-0a4d-4e08-b306-838611cb53be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hot-spot&quot;)</value>
      <webElementGuid>d332ea7c-4b72-446e-bb8f-d06ea533fae4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='hot-spot']</value>
      <webElementGuid>87076abc-f26f-449c-9f7c-802813868108</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div</value>
      <webElementGuid>54e89050-f913-4d72-bdfb-99913a2319d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Context Menu'])[1]/following::div[1]</value>
      <webElementGuid>9bd8e8ec-f40e-4fb1-8aae-74a87b2ac854</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Elemental Selenium'])[1]/preceding::div[1]</value>
      <webElementGuid>c38fd379-97e3-4543-9240-0b5374e39c39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div</value>
      <webElementGuid>0ecca82e-3f31-467d-bb73-873f867e6a42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'hot-spot']</value>
      <webElementGuid>992df0bc-202e-42c4-8c01-a18280b9c75a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
